// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4c81d17e8de07f650cddf73ce751ba8d)
declare namespace Cloudflare {
	interface Env {
		CONTAINER_ORCHESTRATOR: DurableObjectNamespace<import('./../backend/src/index').ContainerOrchestrator>;
		LOVING_CONTAINER: DurableObjectNamespace<import('./../backend/src/index').LovContainer>;
	}
}
interface Env extends Cloudflare.Env {}
